
diagram RegistrationFlow {
  start -> validateEmailAndRole -> createUser
  createUser -> end
}


diagram LoginFlow {
  start -> findUserByEmail
  findUserByEmail -> verifyPasswordAndRole
  verifyPasswordAndRole -> checkProfileCompletion
  checkProfileCompletion: Yes -> redirectToProfileCompletionPage
  checkProfileCompletion: No -> generateJWT
  generateJWT -> end
}


diagram PasswordRecoveryFlow {
  start -> sendRecoveryEmail
  sendRecoveryEmail -> userClicksResetLink
  userClicksResetLink -> validateToken
  validateToken -> displayResetForm
  displayResetForm -> updatePassword
  updatePassword -> end
}
