// Employer Backend Profile Flow
diagram employerBackendProfileFlow {
  start -> registerEmployer
  registerEmployer -> validateRegistration
  validateRegistration -> checkUniqueEmailAndRole
  checkUniqueEmailAndRole -> createUser
  createUser -> respondWithSuccess

  start -> loginEmployer
  loginEmployer -> validateLogin
  validateLogin -> checkUserExists
  checkUserExists -> verifyPassword
  verifyPassword -> checkCompanyId
  checkCompanyId: No -> respondRedirectToCreateCompany
  checkCompanyId: Yes -> generateJWT

  start -> createCompanyProfile
  createCompanyProfile -> validateCompanyData
  validateCompanyData -> createCompanyDocument
  createCompanyDocument -> updateEmployerWithCompanyId
  updateEmployerWithCompanyId -> respondWithSuccess

  start -> updateEmployerProfile
  updateEmployerProfile -> validateUpdateData
  validateUpdateData -> findUserById
  findUserById -> updateUserProfile
  updateUserProfile -> respondWithSuccess

  start -> getCompanyProfile
  getCompanyProfile -> findCompanyById
  findCompanyById -> respondWithCompanyData

  start -> getEmployerProfile
  getEmployerProfile -> findUserById
  findUserById -> respondWithEmployerData
}
